A TensorFlow variable is the recommended way to represent shared, persistent state your program manipulates. This guide covers how to create, update, and manage instances of tf.Variable in TensorFlow.

Variables are created and tracked via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor. Higher level libraries like tf.keras use tf.Variable to store model parameters.

In [1]:
import tensorflow as tf

# Uncomment to see where your variables get placed (see below)
# tf.debugging.set_log_device_placement(True)

In [3]:
# Create a variable
ex_tensor = tf.constant([[1.0, 1.0, 0.0], [9.0, 9.0, 6.0]])
ex_variable = tf.Variable(ex_tensor)

# Variable has the same dtype as the initilized value
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [5]:
print("Shape of Variables: ", ex_variable.shape)
print("DType of Variables: ", ex_variable.dtype)
print("Convert to NumPy: ", ex_variable.numpy())

Shape of Variables:  (2, 3)
DType of Variables:  <dtype: 'float32'>
Convert to NumPy:  [[1. 1. 0.]
 [9. 9. 6.]]


In [8]:
print("A variable:", ex_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(ex_variable))
print("\nIndex of highest value:", tf.argmax(ex_variable))

# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(ex_variable, ([1,6])))

A variable: <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 0.],
       [9., 9., 6.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 1. 0.]
 [9. 9. 6.]], shape=(2, 3), dtype=float32)

Index of highest value: tf.Tensor([1 1 1], shape=(3,), dtype=int64)

Copying and reshaping:  tf.Tensor([[1. 1. 0. 9. 9. 6.]], shape=(1, 6), dtype=float32)


As noted above, variables are backed by tensors. You can reassign the tensor using `tf.Variable.assign`.  Calling `assign` does not (usually) allocate a new tensor; instead, the existing tensor's memory is reused.

In [11]:
a = tf.Variable([2.0, 3.0])
# This will keep the same dtype, float32
a.assign([1, 2]) 
# Not allowed as it resizes the variable: 
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Cannot assign to variable Variable:0 due to variable shape (2,) and value shape (3,) are incompatible


In [12]:
# Although variables are important for differentiation, some variables will not need to be differentiated. You can turn off gradients for a variable by setting trainable to false at creation. An example of a variable that would not need gradients is a training step counter.
counter = tf.Variable(1, trainable=False)

In [13]:
# Set the location of a variable or tensor on one device and do the computation on another device.
# Manual placement 
with tf.device('CPU:0'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])

with tf.device('GPU:0'):
  # Element-wise multiply
  k = a * b

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)


[Distrubuted training](https://github.com/tensorflow/docs/blob/master/site/en/guide/distributed_training.ipynb)